CRUDWithADO/Controllers/BookController.cs
using CRUDWithADO.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CRUDWithADO.Controllers
{
    public class BookController : Controller
    {
        private readonly IConfiguration configuration;
        BookDAL bookDAL;
        public BookController(IConfiguration configuration)
        {
            this.configuration = configuration;
            bookDAL = new BookDAL(this.configuration);
        }
        // GET: BookController
        public IActionResult List()
        {
            var model = bookDAL.GetAllBooks();
            return View(model);
        }

        // GET: BookController/Details/5
        public IActionResult Details(int id)
        {
            var model = bookDAL.GetBookById(id);
            return View(model);

        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book book)
        {
            try
            {
                int result = bookDAL.AddBook(book);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = bookDAL.GetBookById(id);
            return View(model);
        }

        // POST: PersonsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            try
            {
                int result = bookDAL.UpdateBook(book);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = bookDAL.GetBookById(id);
            return View(model);

        }

        // POST: PersonsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                int result = bookDAL.DeleteBook(id);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }
    }
}

CRUDWithADO/Controllers/EmpController.cs
using CRUDWithADO.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore;

namespace CRUDWithADO.Controllers
{
    public class EmpController : Controller
    {
        private readonly IConfiguration configuration;
        EmployeeDAL employeeDAL;
        public EmpController(IConfiguration configuration)
        {
            this.configuration = configuration;
            employeeDAL = new EmployeeDAL(this.configuration);
        }
        // GET: EmpController
        public ActionResult List()
        {
            ViewBag.EmployeeList = employeeDAL.GetAllEmployees();
            return View();
        }

        // GET: EmpController/Details/5
        public ActionResult Details(int id)
        {
            var model = employeeDAL.GetEmployeeById(id);
            return View(model);
        }

        // GET: EmpController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmpController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee emp)
        {
            try
            {
                int result = employeeDAL.AddEmployee(emp);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: EmpController/Edit/5
        public IActionResult Edit(int id)
        {
            var model = employeeDAL.GetEmployeeById(id);
            return View(model);

        }

        // POST: EmpController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Employee emp)
        {
            try
            {
                int result = employeeDAL.UpdateEmployee(emp);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: EmpController/Delete/5
        public IActionResult Delete(int id)
        {
            var model = employeeDAL.GetEmployeeById(id);
            return View(model);

        }

        // POST: EmpController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            try
            {
                int result = employeeDAL.DeleteEmployee(id);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

CRUDWithADO/Controllers/PersonController.cs
using CRUDWithADO.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;


namespace CRUDWithADO.Controllers
{
    public class PersonController : Controller
    {
        private readonly IConfiguration configuration;
        PersonDAL personDAL;
        public PersonController(IConfiguration configuration)
        {
            this.configuration = configuration;
            personDAL = new PersonDAL(this.configuration);
        }
        // GET: PersonController
        public IActionResult List()
        {
            ViewBag.PersonList = personDAL.GetAllPersons();
            return View();
        }

        // GET: PersonController/Details/5
        public IActionResult Details(int id)
        {
            var model = personDAL.GetPersonById(id);
            return View(model);

        }

        // GET: PersonController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PersonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Person person)
        {
            try
            {
                int result = personDAL.AddPerson(person);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: PersonController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = personDAL.GetPersonById(id);
            return View(model);
        }

        // POST: PersonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Person person)
        {
            try
            {
                int result = personDAL.UpdatePerson(person);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: PersonController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = personDAL.GetPersonById(id);
            return View(model);

        }

        // POST: PersonController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                int result = personDAL.DeletePerson(id);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }
    }
}

CRUDWithADO/Controllers/PersonsController.cs
using CRUDWithADO.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CRUDWithADO.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IConfiguration configuration;
        PersonDAL personDAL;
        public PersonsController(IConfiguration configuration)
        {
            this.configuration = configuration;
            personDAL = new PersonDAL(this.configuration);
        }
        // GET: PersonsController
        public IActionResult List()
        {
            var model= personDAL.GetAllPersons();
            return View(model);
        }

        // GET: PersonsController/Details/5
        public IActionResult Details(int id)
        {
            var model = personDAL.GetPersonById(id);
            return View(model);

        }

        // GET: PersonsController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PersonsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Person person)
        {
            try
            {
                int result = personDAL.AddPerson(person);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: PersonsController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = personDAL.GetPersonById(id);
            return View(model);
        }

        // POST: PersonsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Person person)
        {
            try
            {
                int result = personDAL.UpdatePerson(person);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }

        // GET: PersonsController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = personDAL.GetPersonById(id);
            return View(model);

        }

        // POST: PersonsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                int result = personDAL.DeletePerson(id);
                if (result == 1)
                    return RedirectToAction(nameof(List));
                else
                    return BadRequest();
            }
            catch
            {
                return BadRequest();
            }

        }
    }
}

CRUDWithADO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDWithADO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDWithADO.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDWithADO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="List">Employee List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="List">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="List">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="List">Person List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="List">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Register">Register</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CRUDWithADO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>